import Town from '#models/town'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    // Write your database queries inside the run method
    await Town.updateOrCreateMany('id',[
      { id: 1, name: 'BANIKOARA', departmentId: 1 },
      { id: 2, name: 'GOGOUNOU', departmentId: 1 },
      { id: 3, name: 'KANDI', departmentId: 1 },
      { id: 4, name: 'KARIMAMA', departmentId: 1 },
      { id: 5, name: 'MALANVILLE', departmentId: 1 },
      { id: 6, name: 'SEGBANA', departmentId: 1 },
      { id: 7, name: 'BOUKOUMBE', departmentId: 2 },
      { id: 8, name: 'COBLY', departmentId: 2 },
      { id: 9, name: 'KEROU', departmentId: 2 },
      { id: 10, name: 'KOUANDE', departmentId: 2 },
      { id: 11, name: 'MATERI', departmentId: 2 },
      { id: 12, name: 'NATITINGOU', departmentId: 2 },
      { id: 13, name: 'OUASSA-PEHUNCO', departmentId: 2 },
      { id: 14, name: 'TANGUIETA', departmentId: 2 },
      { id: 15, name: 'TOUKOUNTOUNA', departmentId: 2 },
      { id: 16, name: 'ABOMEY-CALAVI', departmentId: 3 },
      { id: 17, name: 'ALLADA', departmentId: 3 },
      { id: 18, name: 'KPOMASSE', departmentId: 3 },
      { id: 19, name: 'OUIDAH', departmentId: 3 },
      { id: 20, name: 'SO-AVA', departmentId: 3 },
      { id: 21, name: 'TOFFO', departmentId: 3 },
      { id: 22, name: 'TORI-BOSSITO', departmentId: 3 },
      { id: 23, name: 'ZE', departmentId: 3 },
      { id: 24, name: 'BEMBEREKE', departmentId: 4 },
      { id: 25, name: 'KALALE', departmentId: 4 },
      { id: 26, name: "N'DALI", departmentId: 4 },
      { id: 27, name: 'NIKKI', departmentId: 4 },
      { id: 28, name: 'PARAKOU', departmentId: 4 },
      { id: 29, name: 'PERERE', departmentId: 4 },
      { id: 30, name: 'SINENDE', departmentId: 4 },
      { id: 31, name: 'TCHAOUROU', departmentId: 4 },
      { id: 32, name: 'BANTE', departmentId: 5 },
      { id: 33, name: 'DASSA-ZOUME', departmentId: 5 },
      { id: 34, name: 'GLAZOUE', departmentId: 5 },
      { id: 35, name: 'OUESSE', departmentId: 5 },
      { id: 36, name: 'SAVALOU', departmentId: 5 },
      { id: 37, name: 'SAVE', departmentId: 5 },
      { id: 38, name: 'APLAHOUE', departmentId: 6 },
      { id: 39, name: 'DJAKOTOMEY', departmentId: 6 },
      { id: 40, name: 'DOGBO', departmentId: 6 },
      { id: 41, name: 'KLOUEKANMEY', departmentId: 6 },
      { id: 42, name: 'LALO', departmentId: 6 },
      { id: 43, name: 'TOVIKLIN', departmentId: 6 },
      { id: 44, name: 'BASSILA', departmentId: 7 },
      { id: 45, name: 'COPARGO', departmentId: 7 },
      { id: 46, name: 'DJOUGOU', departmentId: 7 },
      { id: 47, name: 'OUAKE', departmentId: 7 },
      { id: 48, name: 'COTONOU', departmentId: 8 },
      { id: 49, name: 'ATHIEME', departmentId: 9 },
      { id: 50, name: 'BOPA', departmentId: 9 },
      { id: 51, name: 'COME', departmentId: 9 },
      { id: 52, name: 'GRAND-POPO', departmentId: 9 },
      { id: 53, name: 'HOUEYOGBE', departmentId: 9 },
      { id: 54, name: 'LOKOSSA', departmentId: 9 },
      { id: 55, name: 'ADJARRA', departmentId: 10 },
      { id: 56, name: 'ADJOHOUN', departmentId: 10 },
      { id: 57, name: 'AGUEGUES', departmentId: 10 },
      { id: 58, name: 'AKPRO-MISSERETE', departmentId: 10 },
      { id: 59, name: 'AVRANKOU', departmentId: 10 },
      { id: 60, name: 'BONOU', departmentId: 10 },
      { id: 61, name: 'DANGBO', departmentId: 10 },
      { id: 62, name: 'PORTO-NOVO', departmentId: 10 },
      { id: 63, name: 'SEME-PODJI', departmentId: 10 },
      { id: 64, name: 'ADJA-OUERE', departmentId: 11 },
      { id: 65, name: 'IFANGNI', departmentId: 11 },
      { id: 66, name: 'KETOU', departmentId: 11 },
      { id: 67, name: 'POBE', departmentId: 11 },
      { id: 68, name: 'SAKETE', departmentId: 11 },
      { id: 69, name: 'ABOMEY', departmentId: 12 },
      { id: 70, name: 'AGBANGNIZOUN', departmentId: 12 },
      { id: 71, name: 'BOHICON', departmentId: 12 },
      { id: 72, name: 'COVE', departmentId: 12 },
      { id: 73, name: 'DJIDJA', departmentId: 12 },
      { id: 74, name: 'OUINHI', departmentId: 12 },
      { id: 75, name: 'ZAGNANADO', departmentId: 12 },
      { id: 76, name: 'ZA-KPOTA', departmentId: 12 },
      { id: 77, name: 'ZOGBODOMEY', departmentId: 12 },
    ])
  }
}

