import District from '#models/district'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    // Write your database queries inside the run method
    await District.updateOrCreateMany('id', [
      { id: 1, name: 'FOUNOUGO', townId: 1 },
      { id: 2, name: 'GOMPAROU', townId: 1 },
      { id: 3, name: 'GOUMORI', townId: 1 },
      { id: 4, name: 'KOKEY', townId: 1 },
      { id: 5, name: 'KOKIBOROU', townId: 1 },
      { id: 6, name: 'OUNET', townId: 1 },
      { id: 7, name: 'SOMPEROUKOU', townId: 1 },
      { id: 8, name: 'SOROKO', townId: 1 },
      { id: 9, name: 'TOURA', townId: 1 },
      { id: 10, name: 'BANIKOARA', townId: 1 },
      { id: 11, name: 'BAGOU', townId: 2 },
      { id: 12, name: 'GOUNAROU', townId: 2 },
      { id: 13, name: 'SORI', townId: 2 },
      { id: 14, name: 'SOUGOU-KPAN-TROSSI', townId: 2 },
      { id: 15, name: 'WARA', townId: 2 },
      { id: 16, name: 'GOGOUNOU', townId: 2 },
      { id: 17, name: 'ANGARADEBOU', townId: 3 },
      { id: 18, name: 'BENSEKOU', townId: 3 },
      { id: 19, name: 'DONWARI', townId: 3 },
      { id: 20, name: 'KASSAKOU', townId: 3 },
      { id: 21, name: 'SAAH', townId: 3 },
      { id: 22, name: 'SAM', townId: 3 },
      { id: 23, name: 'SONSORO', townId: 3 },
      { id: 24, name: 'KANDI 1', townId: 3 },
      { id: 25, name: 'KANDI 2', townId: 3 },
      { id: 26, name: 'KANDI 3', townId: 3 },
      { id: 27, name: 'BIRNI LAFIA', townId: 4 },
      { id: 28, name: 'BOGO-BOGO', townId: 4 },
      { id: 29, name: 'KOMPA', townId: 4 },
      { id: 30, name: 'MONSEY', townId: 4 },
      { id: 31, name: 'KARIMAMA', townId: 4 },
      { id: 32, name: 'GAROU', townId: 5 },
      { id: 33, name: 'GUENE', townId: 5 },
      { id: 34, name: 'MADECALI', townId: 5 },
      { id: 35, name: 'TOUMBOUTOU', townId: 5 },
      { id: 36, name: 'MALANVILLE', townId: 5 },
      { id: 37, name: 'LIBANTE', townId: 6 },
      { id: 38, name: 'LIBOUSSOU', townId: 6 },
      { id: 39, name: 'LOUGOU', townId: 6 },
      { id: 40, name: 'SOKOTINDJI', townId: 6 },
      { id: 41, name: 'SEGBANA', townId: 6 },
      { id: 42, name: 'DIPOLI', townId: 7 },
      { id: 43, name: 'KORONTIERE', townId: 7 },
      { id: 44, name: 'KOUSSOUCOINGOU', townId: 7 },
      { id: 45, name: 'MANTA', townId: 7 },
      { id: 46, name: 'NATA', townId: 7 },
      { id: 47, name: 'TABOTA', townId: 7 },
      { id: 48, name: 'BOUKOUMBE', townId: 7 },
      { id: 49, name: 'DATORI', townId: 8 },
      { id: 50, name: 'KOUNTORI', townId: 8 },
      { id: 51, name: 'TAPOGA', townId: 8 },
      { id: 52, name: 'COBLY', townId: 8 },
      { id: 53, name: 'BRIGNAMARO', townId: 9 },
      { id: 54, name: 'FIROU', townId: 9 },
      { id: 55, name: 'KAOBAGOU', townId: 9 },
      { id: 56, name: 'KEROU', townId: 9 },
      { id: 57, name: 'BIRNI', townId: 10 },
      { id: 58, name: 'CHABI-COUMA', townId: 10 },
      { id: 59, name: 'FOO-TANCE', townId: 10 },
      { id: 60, name: 'GUILMARO', townId: 10 },
      { id: 61, name: 'OROUKAYO', townId: 10 },
      { id: 62, name: 'KOUANDE', townId: 10 },
      { id: 63, name: 'DASSARI', townId: 11 },
      { id: 64, name: 'GOUANDE', townId: 11 },
      { id: 65, name: 'NODI', townId: 11 },
      { id: 66, name: 'TANTEGA', townId: 11 },
      { id: 67, name: 'TCHANHOUNCOSSI', townId: 11 },
      { id: 68, name: 'MATERI', townId: 11 },
      { id: 69, name: 'KOTOPOUNGA', townId: 12 },
      { id: 70, name: 'KOUABA', townId: 12 },
      { id: 71, name: 'KOUANDATA', townId: 12 },
      { id: 72, name: 'PERMA', townId: 12 },
      { id: 73, name: 'TCHOUMI-TCHOUMI', townId: 12 },
      { id: 74, name: 'NATITINGOU I', townId: 12 },
      { id: 75, name: 'NATITINGOU II', townId: 12 },
      { id: 76, name: 'NATITINGOU III', townId: 12 },
      { id: 77, name: 'PEPORIYAKOU', townId: 12 },
      { id: 78, name: 'GNEMASSON', townId: 13 },
      { id: 79, name: 'TOBRE', townId: 13 },
      { id: 80, name: 'PEHUNCO', townId: 13 },
      { id: 81, name: 'COTIAKOU', townId: 14 },
      { id: 82, name: "N'DAHONTA", townId: 14 },
      { id: 83, name: 'TAIACOU', townId: 14 },
      { id: 84, name: 'TANONGOU', townId: 14 },
      { id: 85, name: 'TANGUIETA', townId: 14 },
      { id: 86, name: 'KOUARFA', townId: 15 },
      { id: 87, name: 'TAMPEGRE', townId: 15 },
      { id: 88, name: 'TOUKOUNTOUNA', townId: 15 },
      { id: 89, name: 'AKASSATO', townId: 16 },
      { id: 90, name: 'GODOMEY', townId: 16 },
      { id: 91, name: 'GOLO-DJIGBE', townId: 16 },
      { id: 92, name: 'HEVIE', townId: 16 },
      { id: 93, name: 'KPANROUN', townId: 16 },
      { id: 94, name: 'OUEDO', townId: 16 },
      { id: 95, name: 'TOGBA', townId: 16 },
      { id: 96, name: 'ZINVIE', townId: 16 },
      { id: 97, name: 'ABOMEY-CALAVI', townId: 16 },
      { id: 98, name: 'AGBANOU', townId: 17 },
      { id: 99, name: 'AHOUANNONZOUN', townId: 17 },
      { id: 100, name: 'ATTOGON', townId: 17 },
      { id: 101, name: 'AVAKPA', townId: 17 },
      { id: 102, name: 'AYOU', townId: 17 },
      { id: 103, name: 'HINVI', townId: 17 },
      { id: 104, name: 'LISSEGAZOUN', townId: 17 },
      { id: 105, name: 'LON-AGONMEY', townId: 17 },
      { id: 106, name: 'SEKOU', townId: 17 },
      { id: 107, name: 'TOKPA', townId: 17 },
      { id: 108, name: 'ALLADA CENTRE', townId: 17 },
      { id: 109, name: 'TOGOUDO', townId: 17 },
      { id: 110, name: 'AGANMALOME', townId: 18 },
      { id: 111, name: 'AGBANTO', townId: 18 },
      { id: 112, name: 'AGONKANME', townId: 18 },
      { id: 113, name: 'DEDOME', townId: 18 },
      { id: 114, name: 'DEKANME', townId: 18 },
      { id: 115, name: 'SEGBEYA', townId: 18 },
      { id: 116, name: 'SEGBOHOUE', townId: 18 },
      { id: 117, name: 'TOKPA-DOME', townId: 18 },
      { id: 118, name: 'KPOMASSE CENTRE', townId: 18 },
      { id: 119, name: 'AVLEKETE', townId: 19 },
      { id: 120, name: 'DJEGBADJI', townId: 19 },
      { id: 121, name: 'GAKPE', townId: 19 },
      { id: 122, name: 'HOUAKPE-DAHO', townId: 19 },
      { id: 123, name: 'PAHOU', townId: 19 },
      { id: 124, name: 'SAVI', townId: 19 },
      { id: 125, name: 'OUIDAH I', townId: 19 },
      { id: 126, name: 'OUIDAH II', townId: 19 },
      { id: 127, name: 'OUIDAH III', townId: 19 },
      { id: 128, name: 'OUIDAH IV', townId: 19 },
      { id: 129, name: 'AHOMEY-LOKPO', townId: 20 },
      { id: 130, name: 'DEKANMEY', townId: 20 },
      { id: 131, name: 'GANVIE 1', townId: 20 },
      { id: 132, name: 'GANVIE 2', townId: 20 },
      { id: 133, name: 'HOUEDO-AGUEKON', townId: 20 },
      { id: 134, name: 'VEKKY', townId: 20 },
      { id: 135, name: 'SO-AVA', townId: 20 },
      { id: 136, name: 'AGUE', townId: 21 },
      { id: 137, name: 'COLLI', townId: 21 },
      { id: 138, name: 'COUSSI', townId: 21 },
      { id: 139, name: 'DAME', townId: 21 },
      { id: 140, name: 'DJANGLANME', townId: 21 },
      { id: 141, name: 'HOUEGBO', townId: 21 },
      { id: 142, name: 'KPOME', townId: 21 },
      { id: 143, name: 'SEHOUE', townId: 21 },
      { id: 144, name: 'SEY', townId: 21 },
      { id: 145, name: 'TOFFO', townId: 21 },
      { id: 146, name: 'AVAME', townId: 22 },
      { id: 147, name: 'AZOHOUE-ALIHO', townId: 22 },
      { id: 148, name: 'AZOHOUE-CADA', townId: 22 },
      { id: 149, name: 'TORI-CADA', townId: 22 },
      { id: 150, name: 'TORI-GARE', townId: 22 },
      { id: 151, name: 'TORI-BOSSITO', townId: 22 },
      { id: 152, name: 'ADJAN', townId: 23 },
      { id: 153, name: 'DAWE', townId: 23 },
      { id: 154, name: 'DJIGBE', townId: 23 },
      { id: 155, name: 'DODJI-BATA', townId: 23 },
      { id: 156, name: 'HEKANME', townId: 23 },
      { id: 157, name: 'KOUNDOKPOE', townId: 23 },
      { id: 158, name: 'SEDJE-DENOU', townId: 23 },
      { id: 159, name: 'SEDJE-HOUEGOUDO', townId: 23 },
      { id: 160, name: 'TANGBO', townId: 23 },
      { id: 161, name: 'YOKPO', townId: 23 },
      { id: 162, name: 'ZE', townId: 23 },
      { id: 163, name: 'BEROUBOUAY', townId: 24 },
      { id: 164, name: 'BOUANRI', townId: 24 },
      { id: 165, name: 'GAMIA', townId: 24 },
      { id: 166, name: 'INA', townId: 24 },
      { id: 167, name: 'BEMBEREKE', townId: 24 },
      { id: 168, name: 'BASSO', townId: 25 },
      { id: 169, name: 'BOUCA', townId: 25 },
      { id: 170, name: 'DERASSI', townId: 25 },
      { id: 171, name: 'DUNKASSA', townId: 25 },
      { id: 172, name: 'PEONGA', townId: 25 },
      { id: 173, name: 'KALALE', townId: 25 },
      { id: 174, name: 'BORI', townId: 26 },
      { id: 175, name: 'GBEGOUROU', townId: 26 },
      { id: 176, name: 'OUENOU', townId: 26 },
      { id: 177, name: 'SIRAROU', townId: 26 },
      { id: 178, name: "N'DALI", townId: 26 },
      { id: 179, name: 'BIRO', townId: 27 },
      { id: 180, name: 'GNONKOUROKALI', townId: 27 },
      { id: 181, name: 'OUENOU', townId: 27 },
      { id: 182, name: 'SEREKALI', townId: 27 },
      { id: 183, name: 'SUYA', townId: 27 },
      { id: 184, name: 'TASSO', townId: 27 },
      { id: 185, name: 'NIKKI', townId: 27 },
      { id: 186, name: '1ER ARRONDISSEMENT', townId: 28 },
      { id: 187, name: '2EME ARRONDISSEMENT', townId: 28 },
      { id: 188, name: '3EME ARRONDISSEMENT', townId: 28 },
      { id: 189, name: 'GNINSY', townId: 29 },
      { id: 190, name: 'GUINAGOUROU', townId: 29 },
      { id: 191, name: 'KPEBIE', townId: 29 },
      { id: 192, name: 'PANE', townId: 29 },
      { id: 193, name: 'SONTOU', townId: 29 },
      { id: 194, name: 'PERERE', townId: 29 },
      { id: 195, name: 'FO-BOURE', townId: 30 },
      { id: 196, name: 'SEKERE', townId: 30 },
      { id: 197, name: 'SIKKI', townId: 30 },
      { id: 198, name: 'SINENDE', townId: 30 },
      { id: 199, name: 'ALAFIAROU', townId: 31 },
      { id: 200, name: 'BETEROU', townId: 31 },
      { id: 201, name: 'GORO', townId: 31 },
      { id: 202, name: 'KIKA', townId: 31 },
      { id: 203, name: 'SANSON', townId: 31 },
      { id: 204, name: 'TCHATCHOU', townId: 31 },
      { id: 205, name: 'TCHAOUROU', townId: 31 },
      { id: 206, name: 'AGOUA', townId: 32 },
      { id: 207, name: 'AKPASSI', townId: 32 },
      { id: 208, name: 'ATOKOLIBE', townId: 32 },
      { id: 209, name: 'BOBE', townId: 32 },
      { id: 210, name: 'GOUKA', townId: 32 },
      { id: 211, name: 'KOKO', townId: 32 },
      { id: 212, name: 'LOUGBA', townId: 32 },
      { id: 213, name: 'PIRA', townId: 32 },
      { id: 214, name: 'BANTE', townId: 32 },
      { id: 215, name: 'AKOFFODJOULE', townId: 33 },
      { id: 216, name: 'GBAFFO', townId: 33 },
      { id: 217, name: 'KERE', townId: 33 },
      { id: 218, name: 'KPINGNI', townId: 33 },
      { id: 219, name: 'LEMA', townId: 33 },
      { id: 220, name: 'PAOUINGNAN', townId: 33 },
      { id: 221, name: 'SOCLOGBO', townId: 33 },
      { id: 222, name: 'TRE', townId: 33 },
      { id: 223, name: 'DASSA I', townId: 33 },
      { id: 224, name: 'DASSA II', townId: 33 },
      { id: 225, name: 'AKLAMPA', townId: 34 },
      { id: 226, name: 'ASSANTE', townId: 34 },
      { id: 227, name: 'GOME', townId: 34 },
      { id: 228, name: 'KPAKPAZA', townId: 34 },
      { id: 229, name: 'MAGOUMI', townId: 34 },
      { id: 230, name: 'OUEDEME', townId: 34 },
      { id: 231, name: 'SOKPONTA', townId: 34 },
      { id: 232, name: 'THIO', townId: 34 },
      { id: 233, name: 'ZAFFE', townId: 34 },
      { id: 234, name: 'GLAZOUE', townId: 34 },
      { id: 235, name: 'CHALLA-OGOI', townId: 35 },
      { id: 236, name: 'DJEGBE', townId: 35 },
      { id: 237, name: 'GBANLIN', townId: 35 },
      { id: 238, name: 'IKEMON', townId: 35 },
      { id: 239, name: 'KILIBO', townId: 35 },
      { id: 240, name: 'LAMINOU', townId: 35 },
      { id: 241, name: 'ODOUGBA', townId: 35 },
      { id: 242, name: 'TOUI', townId: 35 },
      { id: 243, name: 'OUESSE', townId: 35 },
      { id: 244, name: 'DJALLOUKOU', townId: 36 },
      { id: 245, name: 'DOUME', townId: 36 },
      { id: 246, name: 'GOBADA', townId: 36 },
      { id: 247, name: 'KPATABA', townId: 36 },
      { id: 248, name: 'LAHOTAN', townId: 36 },
      { id: 249, name: 'LEMA', townId: 36 },
      { id: 250, name: 'LOGOZOHE', townId: 36 },
      { id: 251, name: 'MONKPA', townId: 36 },
      { id: 252, name: 'OTTOLA', townId: 36 },
      { id: 253, name: 'OUESSE', townId: 36 },
      { id: 254, name: 'TCHETTI', townId: 36 },
      { id: 255, name: 'SAVALOU-AGA', townId: 36 },
      { id: 256, name: 'SAVALOU-AGBADO', townId: 36 },
      { id: 257, name: 'SAVALOU-ATTAKE', townId: 36 },
      { id: 258, name: 'BESSE', townId: 37 },
      { id: 259, name: 'KABOUA', townId: 37 },
      { id: 260, name: 'OFFE', townId: 37 },
      { id: 261, name: 'OKPARA', townId: 37 },
      { id: 262, name: 'SAKIN', townId: 37 },
      { id: 263, name: 'ADIDO', townId: 37 },
      { id: 264, name: 'BONI', townId: 37 },
      { id: 265, name: 'PLATEAU', townId: 37 },
      { id: 266, name: 'ATOMEY', townId: 38 },
      { id: 267, name: 'AZOVE', townId: 38 },
      { id: 268, name: 'DEKPO-CENTRE', townId: 38 },
      { id: 269, name: 'GODOHOU', townId: 38 },
      { id: 270, name: 'KISSAMEY', townId: 38 },
      { id: 271, name: 'LONKLY', townId: 38 },
      { id: 272, name: 'APLAHOUE', townId: 38 },
      { id: 273, name: 'ADJINTIMEY', townId: 39 },
      { id: 274, name: 'BETOUMEY', townId: 39 },
      { id: 275, name: 'GOHOMEY', townId: 39 },
      { id: 276, name: 'HOUEGAMEY', townId: 39 },
      { id: 277, name: 'KINKINHOUE', townId: 39 },
      { id: 278, name: 'KOKOHOUE', townId: 39 },
      { id: 279, name: 'KPOBA', townId: 39 },
      { id: 280, name: 'SOKOUHOUE', townId: 39 },
      { id: 281, name: 'DJAKOTOMEY I', townId: 39 },
      { id: 282, name: 'DJAKOTOMEY II', townId: 39 },
      { id: 283, name: 'AYOMI', townId: 40 },
      { id: 284, name: 'DEVE', townId: 40 },
      { id: 285, name: 'HONTON', townId: 40 },
      { id: 286, name: 'LOKOGOHOUE', townId: 40 },
      { id: 287, name: 'MADJRE', townId: 40 },
      { id: 288, name: 'TOTCHANGNI CENTRE', townId: 40 },
      { id: 289, name: 'TOTA', townId: 40 },
      { id: 290, name: 'ADJAHONME', townId: 41 },
      { id: 291, name: 'AHOGBEYA', townId: 41 },
      { id: 292, name: 'AYAHOHOUE', townId: 41 },
      { id: 293, name: 'DJOTTO', townId: 41 },
      { id: 294, name: 'HONDJIN', townId: 41 },
      { id: 295, name: 'LANTA', townId: 41 },
      { id: 296, name: 'TCHIKPE', townId: 41 },
      { id: 297, name: 'KLOUEKANME', townId: 41 },
      { id: 298, name: 'ADOUKANDJI', townId: 42 },
      { id: 299, name: 'AHODJINNAKO', townId: 42 },
      { id: 300, name: 'AHOMADEGBE', townId: 42 },
      { id: 301, name: 'BANIGBE', townId: 42 },
      { id: 302, name: 'GNIZOUNME', townId: 42 },
      { id: 303, name: 'HLASSAME', townId: 42 },
      { id: 304, name: 'LOKOGBA', townId: 42 },
      { id: 305, name: 'TCHITO', townId: 42 },
      { id: 306, name: 'TOHOU', townId: 42 },
      { id: 307, name: 'ZALLI', townId: 42 },
      { id: 308, name: 'LALO', townId: 42 },
      { id: 309, name: 'ADJIDO', townId: 43 },
      { id: 310, name: 'AVEDJIN', townId: 43 },
      { id: 311, name: 'DOKO', townId: 43 },
      { id: 312, name: 'HOUEDOGLI', townId: 43 },
      { id: 313, name: 'MISSINKO', townId: 43 },
      { id: 314, name: 'TANNOU-GOLA', townId: 43 },
      { id: 315, name: 'TOVIKLIN', townId: 43 },
      { id: 316, name: 'ALEDJO', townId: 44 },
      { id: 317, name: 'MANIGRI', townId: 44 },
      { id: 318, name: 'PENESSOULOU', townId: 44 },
      { id: 319, name: 'BASSILA', townId: 44 },
      { id: 320, name: 'ANANDANA', townId: 45 },
      { id: 321, name: 'PABEGOU', townId: 45 },
      { id: 322, name: 'SINGRE', townId: 45 },
      { id: 323, name: 'COPARGO', townId: 45 },
      { id: 324, name: 'BAREI', townId: 46 },
      { id: 325, name: 'BARIENOU', townId: 46 },
      { id: 326, name: 'BELLEFOUNGOU', townId: 46 },
      { id: 327, name: 'BOUGOU', townId: 46 },
      { id: 328, name: 'KOLOCONDE', townId: 46 },
      { id: 329, name: 'ONKLOU', townId: 46 },
      { id: 330, name: 'PARTAGO', townId: 46 },
      { id: 331, name: 'PELEBINA', townId: 46 },
      { id: 332, name: 'SEROU', townId: 46 },
      { id: 333, name: 'DJOUGOU I', townId: 46 },
      { id: 334, name: 'DJOUGOU II', townId: 46 },
      { id: 335, name: 'DJOUGOU III', townId: 46 },
      { id: 336, name: 'BADJOUDE', townId: 47 },
      { id: 337, name: 'KOMDE', townId: 47 },
      { id: 338, name: 'SEMERE 1', townId: 47 },
      { id: 339, name: 'SEMERE 2', townId: 47 },
      { id: 340, name: 'TCHALINGA', townId: 47 },
      { id: 341, name: 'OUAKE', townId: 47 },
      { id: 342, name: '1ER ARRONDISSEMENT', townId: 48 },
      { id: 343, name: '2EME ARRONDISSEMENT', townId: 48 },
      { id: 344, name: '3EME ARRONDISSEMENT', townId: 48 },
      { id: 345, name: '4EME ARRONDISSEMENT', townId: 48 },
      { id: 346, name: '5EME ARRONDISSEMENT', townId: 48 },
      { id: 347, name: '6EME ARRONDISSEMENT', townId: 48 },
      { id: 348, name: '7EME ARRONDISSEMENT', townId: 48 },
      { id: 349, name: '8EME ARRONDISSEMENT', townId: 48 },
      { id: 350, name: '9EME ARRONDISSEMENT', townId: 48 },
      { id: 351, name: '10EME ARRONDISSEMENT', townId: 48 },
      { id: 352, name: '11EME ARRONDISSEMENT', townId: 48 },
      { id: 353, name: '12EME ARRONDISSEMENT', townId: 48 },
      { id: 354, name: '13EME ARRONDISSEMENT', townId: 48 },
      { id: 355, name: 'ADOHOUN', townId: 49 },
      { id: 356, name: 'ATCHANNOU', townId: 49 },
      { id: 357, name: 'DEDEKPOE', townId: 49 },
      { id: 358, name: 'KPINNOU', townId: 49 },
      { id: 359, name: 'ATHIEME', townId: 49 },
      { id: 360, name: 'AGBODJI', townId: 50 },
      { id: 361, name: 'BADAZOUIN', townId: 50 },
      { id: 362, name: 'GBAKPODJI', townId: 50 },
      { id: 363, name: 'LOBOGO', townId: 50 },
      { id: 364, name: 'POSSOTOME', townId: 50 },
      { id: 365, name: 'YEGODOE', townId: 50 },
      { id: 366, name: 'BOPA', townId: 50 },
      { id: 367, name: 'AGATOGBO', townId: 51 },
      { id: 368, name: 'AKODEHA', townId: 51 },
      { id: 369, name: 'OUEDEME-PEDAH', townId: 51 },
      { id: 370, name: 'OUMAKO', townId: 51 },
      { id: 371, name: 'COME', townId: 51 },
      { id: 372, name: 'ADJAHA', townId: 52 },
      { id: 373, name: 'AGOUE', townId: 52 },
      { id: 374, name: 'AVLO', townId: 52 },
      { id: 375, name: 'DJANGLANMEY', townId: 52 },
      { id: 376, name: 'GBEHOUE', townId: 52 },
      { id: 377, name: 'SAZUE', townId: 52 },
      { id: 378, name: 'GRAND-POPO', townId: 52 },
      { id: 379, name: 'DAHE', townId: 53 },
      { id: 380, name: 'DOUTOU', townId: 53 },
      { id: 381, name: 'HONHOUE', townId: 53 },
      { id: 382, name: 'ZOUNGBONOU', townId: 53 },
      { id: 383, name: 'HOUEYOGBE', townId: 53 },
      { id: 384, name: 'SE', townId: 53 },
      { id: 385, name: 'AGAME', townId: 54 },
      { id: 386, name: 'HOUIN', townId: 54 },
      { id: 387, name: 'KOUDO', townId: 54 },
      { id: 388, name: 'OUEDEME-ADJA', townId: 54 },
      { id: 389, name: 'LOKOSSA', townId: 54 },
      { id: 390, name: 'AGLOGBE', townId: 55 },
      { id: 391, name: 'HONVIE', townId: 55 },
      { id: 392, name: 'MALANHOUI', townId: 55 },
      { id: 393, name: 'MEDEDJONOU', townId: 55 },
      { id: 394, name: 'ADJARRA 1', townId: 55 },
      { id: 395, name: 'ADJARRA 2', townId: 55 },
      { id: 396, name: 'AKPADANOU', townId: 56 },
      { id: 397, name: 'AWONOU', townId: 56 },
      { id: 398, name: 'AZOWLISSE', townId: 56 },
      { id: 399, name: 'DEME', townId: 56 },
      { id: 400, name: 'GANGBAN', townId: 56 },
      { id: 401, name: 'KODE', townId: 56 },
      { id: 402, name: 'TOGBOTA', townId: 56 },
      { id: 403, name: 'ADJOHOUN', townId: 56 },
      { id: 404, name: 'AVAGBODJI', townId: 57 },
      { id: 405, name: 'HOUEDOME', townId: 57 },
      { id: 406, name: 'ZOUNGAME', townId: 57 },
      { id: 407, name: 'GOME-SOTA', townId: 58 },
      { id: 408, name: 'KATAGON', townId: 58 },
      { id: 409, name: 'VAKON', townId: 58 },
      { id: 410, name: 'ZOUNGBOME', townId: 58 },
      { id: 411, name: 'AKPRO-MISSERETE', townId: 58 },
      { id: 412, name: 'ATCHOUKPA', townId: 59 },
      { id: 413, name: 'DJOMON', townId: 59 },
      { id: 414, name: 'GBOZOUME', townId: 59 },
      { id: 415, name: 'KOUTI', townId: 59 },
      { id: 416, name: 'OUANHO', townId: 59 },
      { id: 417, name: 'SADO', townId: 59 },
      { id: 418, name: 'AVRANKOU', townId: 59 },
      { id: 419, name: 'AFFAME', townId: 60 },
      { id: 420, name: 'ATCHONSA', townId: 60 },
      { id: 421, name: 'DAME-WOGON', townId: 60 },
      { id: 422, name: 'HOUNVIGUE', townId: 60 },
      { id: 423, name: 'BONOU', townId: 60 },
      { id: 424, name: 'DEKIN', townId: 61 },
      { id: 425, name: 'GBEKO', townId: 61 },
      { id: 426, name: 'HOUEDOMEY', townId: 61 },
      { id: 427, name: 'HOZIN', townId: 61 },
      { id: 428, name: 'KESSOUNOU', townId: 61 },
      { id: 429, name: 'ZOUNGUE', townId: 61 },
      { id: 430, name: 'DANGBO', townId: 61 },
      { id: 431, name: '1ER ARRONDISSEMENT', townId: 62 },
      { id: 432, name: '2EME ARRONDISSEMENT', townId: 62 },
      { id: 433, name: '3EME ARRONDISSEMENT', townId: 62 },
      { id: 434, name: '4EME ARRONDISSEMENT', townId: 62 },
      { id: 435, name: '5EME ARRONDISSEMENT', townId: 62 },
      { id: 436, name: 'AGBLANGANDAN', townId: 63 },
      { id: 437, name: 'AHOLOUYEME', townId: 63 },
      { id: 438, name: 'DJEREGBE', townId: 63 },
      { id: 439, name: 'EKPE', townId: 63 },
      { id: 440, name: 'TOHOUE', townId: 63 },
      { id: 441, name: 'SEME-PODJI', townId: 63 },
      { id: 442, name: 'IKPINLE', townId: 64 },
      { id: 443, name: 'KPOULOU', townId: 64 },
      { id: 444, name: 'MASSE', townId: 64 },
      { id: 445, name: 'OKO-AKARE', townId: 64 },
      { id: 446, name: 'TATONNONKON', townId: 64 },
      { id: 447, name: 'ADJA-OUERE', townId: 64 },
      { id: 448, name: 'BANIGBE', townId: 65 },
      { id: 449, name: 'DAAGBE', townId: 65 },
      { id: 450, name: 'KO-KOUMOLOU', townId: 65 },
      { id: 451, name: 'LAGBE', townId: 65 },
      { id: 452, name: 'TCHAADA', townId: 65 },
      { id: 453, name: 'IFANGNI', townId: 65 },
      { id: 454, name: 'ADAKPLAME', townId: 66 },
      { id: 455, name: 'IDIGNY', townId: 66 },
      { id: 456, name: 'KPANKOU', townId: 66 },
      { id: 457, name: 'ODOMETA', townId: 66 },
      { id: 458, name: 'OKPOMETA', townId: 66 },
      { id: 459, name: 'KETOU', townId: 66 },
      { id: 460, name: 'AHOYEYE', townId: 67 },
      { id: 461, name: 'IGANA', townId: 67 },
      { id: 462, name: 'ISSABA', townId: 67 },
      { id: 463, name: 'TOWE', townId: 67 },
      { id: 464, name: 'POBE', townId: 67 },
      { id: 465, name: 'AGUIDI', townId: 68 },
      { id: 466, name: 'ITA-DJEBOU', townId: 68 },
      { id: 467, name: 'TAKON', townId: 68 },
      { id: 468, name: 'YOKO', townId: 68 },
      { id: 469, name: 'SAKETE 1', townId: 68 },
      { id: 470, name: 'SAKETE 2', townId: 68 },
      { id: 471, name: 'AGBOKPA', townId: 69 },
      { id: 472, name: 'DETOHOU', townId: 69 },
      { id: 473, name: 'SEHOUN', townId: 69 },
      { id: 474, name: 'ZOUNZONME', townId: 69 },
      { id: 475, name: 'DJEGBE', townId: 69 },
      { id: 476, name: 'HOUNLI', townId: 69 },
      { id: 477, name: 'VIDOLE', townId: 69 },
      { id: 478, name: 'ADANHONDJIGO', townId: 70 },
      { id: 479, name: 'ADINGNIGON', townId: 70 },
      { id: 480, name: 'KINTA', townId: 70 },
      { id: 481, name: 'KPOTA', townId: 70 },
      { id: 482, name: 'LISSAZOUNME', townId: 70 },
      { id: 483, name: 'SAHE', townId: 70 },
      { id: 484, name: 'SINWE', townId: 70 },
      { id: 485, name: 'TANVE', townId: 70 },
      { id: 486, name: 'ZOUNGOUNDO', townId: 70 },
      { id: 487, name: 'AGBANGNIZOUN', townId: 70 },
      { id: 488, name: 'AGONGOINTO', townId: 71 },
      { id: 489, name: 'AVOGBANNA', townId: 71 },
      { id: 490, name: 'GNIDJAZOUN', townId: 71 },
      { id: 491, name: 'LISSEZOUN', townId: 71 },
      { id: 492, name: 'OUASSAHO', townId: 71 },
      { id: 493, name: 'PASSAGON', townId: 71 },
      { id: 494, name: 'SACLO', townId: 71 },
      { id: 495, name: 'SODOHOME', townId: 71 },
      { id: 496, name: 'BOHICON I', townId: 71 },
      { id: 497, name: 'BOHICON II', townId: 71 },
      { id: 498, name: 'HOUEKO', townId: 72 },
      { id: 499, name: 'ADOGBE', townId: 72 },
      { id: 500, name: 'GOUNLI', townId: 72 },
      { id: 501, name: 'HOUIN-HOUNSO', townId: 72 },
      { id: 502, name: 'LAINTA-COGBE', townId: 72 },
      { id: 503, name: 'NAOGON', townId: 72 },
      { id: 504, name: 'SOLI', townId: 72 },
      { id: 505, name: 'ZOGBA', townId: 72 },
      { id: 506, name: 'AGONDJI', townId: 73 },
      { id: 507, name: 'AGOUNA', townId: 73 },
      { id: 508, name: 'DAN', townId: 73 },
      { id: 509, name: 'DOHOUIME', townId: 73 },
      { id: 510, name: 'GOBAIX', townId: 73 },
      { id: 511, name: 'HOUTO', townId: 73 },
      { id: 512, name: 'MONSOUROU', townId: 73 },
      { id: 513, name: 'MOUGNON', townId: 73 },
      { id: 514, name: 'OUMBEGAME', townId: 73 },
      { id: 515, name: 'SETTO', townId: 73 },
      { id: 516, name: 'ZOUNKON', townId: 73 },
      { id: 517, name: 'DJIDJA CENTRE', townId: 73 },
      { id: 518, name: 'DASSO', townId: 74 },
      { id: 519, name: 'SAGON', townId: 74 },
      { id: 520, name: 'TOHOUES', townId: 74 },
      { id: 521, name: 'OUINHI CENTRE', townId: 74 },
      { id: 522, name: 'AGONLIN-HOUEGBO', townId: 75 },
      { id: 523, name: 'BANAME', townId: 75 },
      { id: 524, name: 'DON-TAN', townId: 75 },
      { id: 525, name: 'DOVI', townId: 75 },
      { id: 526, name: 'KPEDEKPO', townId: 75 },
      { id: 527, name: 'ZAGNANADO CENTRE', townId: 75 },
      { id: 528, name: 'ALLAHE', townId: 76 },
      { id: 529, name: 'ASSANLIN', townId: 76 },
      { id: 530, name: 'HOUNGOME', townId: 76 },
      { id: 531, name: 'KPAKPAME', townId: 76 },
      { id: 532, name: 'KPOZOUN', townId: 76 },
      { id: 533, name: 'ZA-TANTA', townId: 76 },
      { id: 534, name: 'ZEKO', townId: 76 },
      { id: 535, name: 'ZA-KPOTA', townId: 76 },
      { id: 536, name: 'AKIZA', townId: 77 },
      { id: 537, name: 'AVLAME', townId: 77 },
      { id: 538, name: 'CANA I', townId: 77 },
      { id: 539, name: 'CANA II', townId: 77 },
      { id: 540, name: 'DOME', townId: 77 },
      { id: 541, name: 'KOUSSOUKPA', townId: 77 },
      { id: 542, name: 'KPOKISSA', townId: 77 },
      { id: 543, name: 'MASSI', townId: 77 },
      { id: 544, name: 'TANWE-HESSOU', townId: 77 },
      { id: 545, name: 'ZOUKOU', townId: 77 },
      { id: 546, name: 'ZOGBODOMEY CENTRE', townId: 77 },
    ])
  }
}
